query StepContent($stepId: ID!) {
  contentByStepId(id: $stepId) {
    ... on BaseContent {
      id
    }
    ... on HtmlBodyContent {
      bodyForMobileApp
      copyrightForMobileApp
    }
    ... on VideoArticle {
      video {
        hlsUrl
        posterImageUrl
        status
        englishTranscript {
          paragraphs {
            timestamp
            text
          }
        }
      }
    }
  }
}
