query YourCourses {
  currentUser {
    id
    firstName
    hasSubscriptions
    activeCourseEnrolments {
      id
      createdAt
      run {
        id
        fullTitle
        imageUrl
        course {
          organisation {
            title
          }
        }
      }
    }
  }
}
